### ISSUE TITLE
how does audio work?

### ISSUE THREAD

**Issue by antgame11** [ayunami2000/ayunMCVNC#1]
really cool project but how do I get audio working?

**Comment by ayunami2000** [comment]
Ok so basically, install ffmpeg, then, in a command prompt, run:
`ffmpeg -y -re -stream_loop -1 -thread_queue_size 4096 -i "https://siloh.pluto.tv/lilo/production/Nick/01/master.m3u8" -vf scale=512:256 -f rawvideo -c:v mjpeg -qscale:v 16 -r 20 udp://127.0.0.1:1337 -f s16le -acodec pcm_s16le -ac 2 -ar 48000 udp://127.0.0.1:1338`

Then, in game, while looking at the top left corner of where the screen will be, do:
`/mcvnc create fard 4 2 false 1000 1337;1338`

Now, place the item frames if you haven't already, and put the maps into the item frames (if there were already maps there, either break them via breaking the block behind them, or by temporarily moving [`/mcvnc move @`] the display [looking at a different block to move it to there])

Now, navigate to port `8819`; e.g., http://localhost:8819, and then click connect! The rest of the process explains itself.
